### ISSUE TITLE
Population system

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#20]
Implement pop growth, assignation, training units, pop yields, etc.

Pop species like stellaris? Some civs capture pops while others can only kill them / eat them?

**Comment by JayToDaBee** [comment]
Races can now be defined json, and can now add/remove pop of a given race in cities

Adding a pop is relatively straightforward, removing one requires to check whether there is one to remove, if it was busy (it unbusies it), etc. Added temporary buttons to control the population size of humans and orcs in city screen. Done on branch rose/populationsystem

This issue and #21 will probably be very interlinked

**Comment by JayToDaBee** [comment]
Pops now consume Food, and Growth is calculated from it, by taking the root of the excess food per turn and multiplying it by a base value (which is currently 1). Specialists can now have a race assigned to them, and this race is taken from the available ones in the idle pool. Population is increased by 1 unit of the civ's base race when Growth reaches target growth (currently 10). In case of massive growth output, it is theoretically feasible to get or lose more than one pop per turn using this mechanism, although the square root factor would mean you need over 100 extra food per turn with the current values.

Commit: 48d8a5e

Next step: UI to make this easily readable in the city screen

**Comment by JayToDaBee** [comment]
Growth is now functional and visible in city screen (95bea30).

Will keep the training of units for the future, closing this.
