### ISSUE TITLE
Tiles V3

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#22]
- Drawing all tile variations in autocad
- Modeling tiles
- Cliffs for ramps

**Comment by scaryrabbit** [comment]
Finished all new tiles. Heres the naming convention : 

### Tiles
**SM_Hex_(Tile type)_(Neighbors)_(Rivers)_(Variation number)**
ie SM_Hex_L_0WW000_XXXOWX_1

Tile types are :
**W** for water tile
**L** for land tile
**S** for a river source tile.

Neighbors are a combination of 6 characters referencing all neighboring tiles starting to the right and going counterclockwise :
**W** stands for a water neighbor
**R** stands for a ramp
**T** stands for the top of a ramp and as such a tile at a higher elevation

Rivers are a combination of 6 characters referencing rivers connected to neighboring tiles starting to the right and going counterclockwise :
**I** stands for a river coming into the tile
**O** stands for a river going out of the tile
**W** stands for a waterfall, a river coming in at a higher elevation

Variation number starts at 1.

### Cliffs
**SM_Cliff_(Cliff type)_(Variation)**
ie SM_Cliff_cCWx_01

Cliff type is a combination of 3 identifiers representing a cliff section's left neighbor, the cliff section in capitals followed by the cliff section's right neighbor. The various identifiers are :
Neighbors :
**x** for no neighboring cliff inside the tile
**c** for a neighboring cliff inside the tile
**t** for a neighboring section at the top of a ramp

Cliff section :
C for a cliff section without a waterfall
CW for a cliff section with a waterfall

Variation number starts at 01. Because.

**Comment by JayToDaBee** [comment]
2 comments:
-Why differentiate source tiles from land tiles? Why can they not just be L tiles with a single out? from my side I don't see why that would be relevant
-CW should be changed to a single character (I'd suggest W) this makes for much simpler parsing on my side

**Comment by scaryrabbit** [comment]
That's what I had at first, but then I had to name a source tile where the river was going straight into a lake and there is no Out there. For these tile, the Source identifier is the only indication there is a river.

I will change the waterfall cliff identifier to be only W. I will update my long comment with the changes so that's there aren't 3 versions of that post.

**Comment by scaryrabbit** [comment]
Updated naming convention post with standalone ramp cliff.

**Comment by JayToDaBee** [comment]
Which material should be applied to the cliffs?

**Comment by scaryrabbit** [comment]
Same material as the tiles. That might end up changing later, but for now they are mapped on part of the tiles' texture.

**Comment by JayToDaBee** [comment]
The new cliffs are now integrated in the map, haven't found any glaring bugs for now.

To do:
-implement the sources for rivers
-make more generous and varied procedures for ramp generation, which take into account the new half cliffs possibility
-store cliff data in the hextiles, or pass it directly at generation instead of computing it at initialization?
-debug and reactivate feature placement at generation (possibly also in cities)
-regenerate HexSpotsGeometry.json, and post-process it in real-time to account for cliffs

Commit: a8807ead10cfdfac8398dae84cbade93b49bdae3

**Comment by JayToDaBee** [comment]
Is it possible that the cCx-xCt connection doesn't quite clamp together?

![Screenshot (27)](https://user-images.githubusercontent.com/20506343/108120016-a01e8400-706e-11eb-9252-d36f4f9c72c6.png)

**Comment by scaryrabbit** [comment]
Spotted the same thing while looking at the map on the TilesV3 branch. Found 2 issues in my cliff meshes, one extending over a neighbor (which isn't apparent) and one missing some geometry, which is what you're looking at.

Will have a fix ready in maybe 5 mins.

**Comment by JayToDaBee** [comment]
Just thought about a case that we didn't discuss: ramp tiles where a waterfall arrives at the bottom of the ramp. If I'm counting correctly, this should amount to 20-40 tiles. Do we want them?

**Comment by JayToDaBee** [comment]
Some ramps appear not to clamp perfectly at the top: 
![Screenshot (29)_LI](https://user-images.githubusercontent.com/20506343/108313739-cd5e5580-7186-11eb-9feb-25467fd611ee.jpg)

**Comment by scaryrabbit** [comment]
I have no clue what the issue is from that picture.

**Comment by scaryrabbit** [comment]
> Just thought about a case that we didn't discuss: ramp tiles where a waterfall arrives at the bottom of the ramp. If I'm counting correctly, this should amount to 20-40 tiles. Do we want them?

Counted on my end, I think that would be 18 tiles. Should be quick enough to do.

**Comment by scaryrabbit** [comment]
![Bug](https://user-images.githubusercontent.com/6887591/108400787-a08f5a00-71e9-11eb-8654-7c94e8e4ce03.PNG)

Figure that shit out champ.

**Comment by scaryrabbit** [comment]
Just pushed all ramp tiles with waterfalls. Let me know if you run into any issues.

Commit : 2fbec25121dd4494a0d00221db37184717ac0ddd

**Comment by JayToDaBee** [comment]
What about sources in ramps? Don't remember talking about those. Quick count says about 28 cases.

**Comment by scaryrabbit** [comment]
It's probably one day of work or so to support it. Not something I deem prohibitive if we want it.

**Comment by JayToDaBee** [comment]
The xRc-cCx has some weird angles to it at the top:

![Screenshot (31)](https://user-images.githubusercontent.com/20506343/108611578-c7968900-73ad-11eb-86ea-bcbb798852af.png)

**Comment by JayToDaBee** [comment]
> -implement the sources for rivers
Done.

Fixed and expanded river generation with new tile system

    This includes:
-rivers have sources
-rivers don't go over half-cliffs anymore
-rivers can now fork when cliffs are present (just not in the direction of the cliffs)
-rivers won't end when directly next to an eligible lake connection anymore
-reduced river segment length, might still be too long

Not done yet: expand the array of available starting tiles for rivers by accepting to start also on ramps. If it takes only approximately one day to generate the ramp sources, then I'd wait for those and do it after they are done, should be relatively straightforward anyways.

commit: c2c57a3a1e552d5b9f9826cbbbe8f171fe906e6b

By the way, have a look at the cross-ramps case. You can find it on the right of the map with 1681377408 and default settings. Or on these pics, but not super visible.
![Screenshot (35)](https://user-images.githubusercontent.com/20506343/108612481-2280ae00-73b7-11eb-8e5d-65a2e98207f4.png)
![Screenshot (34)](https://user-images.githubusercontent.com/20506343/108612483-23194480-73b7-11eb-8fdc-1bd1f5763682.png)

**Comment by scaryrabbit** [comment]
My feeling is that as is, it looks very meh. Do you think gameplay wise it is interesting? Definitely think that it adds options for the map generation, not sure it is necessary though.

**Comment by JayToDaBee** [comment]
At the moment it us much easier to keep than to remove. I say we keep it, and if we want to remove it it shouldn't be harder to do then than now.

**Comment by scaryrabbit** [comment]
Yeah, my main issue with it is that there are 2 spots on each ramp that seem clear but that should show up as cliffs unless we make an exception for it (where the cliff mesh is actually under the other ramp).

**Comment by JayToDaBee** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/20506343/108671525-9651b200-74ae-11eb-9aef-82c609244f61.png)

Better.

**Comment by scaryrabbit** [comment]
Yeah, much better for the cross ramps.

Also, just pushed all source ramp tiles.

**Comment by scaryrabbit** [comment]
As of commit 3c9c202a25be04d69f11e7d47299f4fc61f2452d

there shouldn't be any weird angles at the top of Cc and cC connections. Let me know if you spot any other case of this.

**Comment by JayToDaBee** [comment]
I just merged with master on the branch btw, all features should be functional (use a flat 000000 tile for tests, others may not have properly defined base spots for now, this is what I'm doing now)

**Comment by JayToDaBee** [comment]
-Generating HexSpotsGeometry does not cause to explode the RAM anymore, although it still takes a while because of combinatorics (whatever I do, 2* 4^12 cases is gonna remain big :P )
-Generated a new HexSpotsGeometry.json file, which is mostly correct; need to manually place the cascades (ramp rivers)
-Rewrote the RiverOn123456 arrays into a single RiverOnX array of arrays, which notably allows to simplify many places in the code and give easy access to each hex to his own rivers
-Base spot calculation now uses the getBaseSpotWithCliffs function, which reads from HexSpotsGeometry and superposes cliffs and waterfalls on top of it. Note that getBaseSpotNoCliffs is also available if one only wants the HexSpotsGeometry value, but I might revoke this access later, as I don't really see why one would need it.
-Removed restrictions on rivers starting and ending on ramps
-HexSpotManager now always traces to determine the height of a spot (no reason not to, and it simplifies it quite a bit)

Commit: c9c1a39970663697fc46db18c86bc2e2e3a11d39

Overall, the new tile system is pretty much ready to go, except the couple cases listed in #11, the cascades spot info, and the ramp corner case. Will open new issues for the latter 2; keep your eyes open if you see some spots which are not what they should be. Closing this for now.

**Comment by JayToDaBee** [comment]
Merged to master

**Comment by JayToDaBee** [comment]
@scaryrabbit from my side this is done, I would close the branch and continue on another.
