### ISSUE TITLE
Construction system

### ISSUE THREAD

**Issue by JayToDaBee** [JayToDaBee/TwelveAngryNodes_4.24#23]
I need to implement a system in which the constructible features do not appear instantly, but rather go through a phase of being built up first. At the moment I'm thinking that a first approximation of such a thing would be:

-Buildings have a construction cost in materials-could be modified?
-Pops need to be assigned to the site for it to progress
-Pops have a base "materials transfer rate" from the cities' material income to the building, say up to x/turn-should be boostable
-The base number of pops that can be assigned depends on the size in spots (i.e 3 spots 3 potential pops)-should be boostable

**Comment by JayToDaBee** [comment]
Material cost to features is now definable, and including one modifies the initial state of a feature.

The appearance of features is modified according to their "Feature State", provided the assets with the same path as those of the base assets with a "_Unfinished" suffix exist; if they don't the base asset is used. The city screen hover over a spot now indicates the state of a given feature if it is different from nominal.

See c62323b77f2e7b6b57a25dbdc64cbb83be70aca3

**Comment by scaryrabbit** [comment]
TODO: add more levels of unfinished, and rename to _U1 _U2 _U3

**Comment by JayToDaBee** [comment]
A summary of what is done up to now:

-Buildings have a construction cost in materials (cannot be modified for now)
-Features now have a json-defined max life
-Pops need to be assigned to the site for it to progress (i.e. their life will increase)
-Features which have a construction cost will be placed as VE_Unfinished1 (_U1) with 0 life, and the pops assigned to it will make it progress through VE_Unfinished2 (_U2) and VE_Unfinished3 (_U3) to Finished; different materials and meshes can be applied by applying the appropriate suffix (in parentheses) to the asset name, e.g., SM_Mine_U1.uasset would be the first stage of progression of the SM_Mine.uasset. Note that not all these extra meshes/materials need to exist; if they don't, the game automatically looks for a replacement (U3 looks for U2 looks for U1 looks for the base asset).
-Civs must define a BaseBuilder, which should have a base BuildingYieldEffectTag which indicates the correct yieldeffect to use from the cities' material income to the building; this builder is then used for all building sites in the empire (the materials rate is treated as a yieldeffect and is as such boostable)
-The base number of pops that can be assigned depends on the size in spots (currently not boostable)
-Changed default behavior of YieldEffect Tags so that: no tags = no effect
-The construction phase happens between player turns, specifically at the end of the turn of the player; eventually this will need to be moved to be simultaneous for all players
-Up to what I could find, all specialists interactions happen properly (i.e. no disappearing pop, specialists stay assigned when they should (and don't when they shouldn't, such as when a feature finishes), etc.)
-In-game, the current feature state can be seen by hovering over a spot in the city screen, in the list of features on this spot in the topleft corner
-Although stockpiles have been defined, they currently have no gameplay effect, as no checks are performed whatsoever as to whether enough materials are present/produced

Next steps:
-Figure out how to modify/boost the number of specialists in features in an elegant fashion
-Simulteanize atEndTurn for all players
-Normalize the use of materials in some simple but regulated fashion, so that the player must take into account some constraints to build stuff

The first 2 deserve their own issues, as these are larger problems than just for the construction system. Will work on the third one in this issue.

Commits :
c62323b77f2e7b6b57a25dbdc64cbb83be70aca3
e30359861ef1a7a00f4efcbe9a79315f0f2755a6
fc605aaa85a6f88db09d056e55391e707067af49
33c110c0b87b67dd172e292f9499eb2bff5aa600
7d5239d1552e8bf57e4ff2543cb28a7723dc5ec1
d37b332b26f116ee47e8daf8c901f4a24d522943
596e06b6335909c9dcd9d411848d80318a6c72da
b53545b103d1a9baed95428244c0d5a011b5a35e
6f4315b2d9a3b3fbe2d7280f31151ce47ce8c49e
b18a9ca35a28356d81db2b1822e6ee30afa9897f
bb10c364ef7a8df17828e0f5eef57d27ea505328
69c598628b46b79ef6dcac4413ce768ecba05672

**Comment by JayToDaBee** [comment]
Opened #29 and #30

**Comment by JayToDaBee** [comment]
Implemented basics of a constraint system for building features

If there is not enough materials for all, creates a list of all negative contributions at end turn. Selects one randomly:
    -deactivates it if it is a specialist
    -hurts a feature if it is a feature (life loss)
Rinse and repeat until there is enough materials for all remaining negative contributions.

Also:
-Stockpiles are now visible next to the yield of their type
-Life of features is now displayed on spot hover
-Cities start with 50 (because its a nice number) materials and need to find more to be able to build for a longer period, currently either using a lumbermill or a mine.

Everything seems to be working and is debugged as far as I can tell. Closing this and merging to master.

Commits:
40df47d4c2a4d6206391e6af89ca0714eae80d84
e4cd2a8d809fbb2ea0d34b7d0244e0e340756fb8
