### ISSUE TITLE
Cliffs - standalone ramp

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#25]
Create cliffs for a ramp that isn't sandwiched between tiles at a higher elevation.

Fix cliffs used for ramps so they occupy the whole spots they are supposed to block.

**Comment by scaryrabbit** [comment]
![CliffRampWip](https://user-images.githubusercontent.com/6887591/107134980-e896ae80-68c4-11eb-9d90-e78b63d12aab.PNG)

Wip standalone ramp for cliffs. Should get everything named properly and pushed tonight or tomorrow.

**Comment by scaryrabbit** [comment]
![CliffRampWip2](https://user-images.githubusercontent.com/6887591/107137109-21d81a00-68d7-11eb-83dd-d1d572ad30f0.PNG)

Finished tweaking cliffs for ramps. Made them thicker where slopes are higher so they visually cover the whole spots they occupy.

Do note the spots occupied and left open for standalone ramps.

**Comment by JayToDaBee** [comment]
> Do note the spots occupied and left open for standalone ramps.

Noted. This is relatively simple to implement, as 2 standalone ramps will never be next to each other; just put the central 3 spots of that side as cliffs instead of all 5.
