### ISSUE TITLE
Update DOC_Resources

### ISSUE THREAD

**Issue by JayToDaBee** [JayToDaBee/TwelveAngryNodes_4.24#32]
This is not up to date, and should be. Many infos missing

**Comment by JayToDaBee** [comment]
I've just updated DOC_Resources (and renamed prod->materials) on master. @scaryrabbit have a look and close the issue if you have no more questions, else let me know what isn't clear

**Comment by scaryrabbit** [comment]
Looked it through, seems pretty clear.
