### ISSUE TITLE
Cliffs misplacing

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#38]
Ramp cliff placed between 2 tiles at same height without ramp.

![Bug](https://user-images.githubusercontent.com/6887591/109053945-4855cd80-76ab-11eb-863a-b49f6d598445.PNG)

Master branch
Commit : 7fc3ded

**Comment by JayToDaBee** [comment]
Fixed in 2667e10ea49cdb295f5dc4e6f69e91cb227883b8
