### ISSUE TITLE
Harvest and clear feature system with jobs

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#40]
Need a feature harvest and removal system that goes through jobs

-harvest removes life from feature
-environment gives some back? (for some? fertility related)
-clear gives no resources but makes space available fast (removes more life)

**Comment by JayToDaBee** [comment]
Resources now harvestable through json

Features can be assigned a list of 'HarvestYields' from which only
range=local have an effect; those yields can then be used using
harvesters, which are spawned from a special harvest feature. The yields
of harversters depends on the HarvestYields of the harvested feature.

Commit: 9b8ee4c103aad878961e6ee0c22bdc2f7b4f15b6

**Comment by JayToDaBee** [comment]
Harvesters do not yet remove life from their associated feature.

**Comment by JayToDaBee** [comment]
Commit: f79648f

Harvesters now remove life from their associated feature.

If the feature has no life left, the harvester is removed. If there are no more harvesters, the harvest feature is removed. Multiple harvesters can be spawned if there is more than one harvestable feature on the spot. Multitile features can have one harvester per tile assigned to them, and their effects are cumulative.

AdjustPopulation moved to before the computation of materials for features.

Feature state system updated:
-Features which are being built still go through the previous unfinished states
-Features which are finished and lose life become broken; broken features retain their specialists and gain a builder to repair it if player-built.
-Features which go below 50% life become ruined; ruined features lose their specialists and properties and cannot be repaired anymore.
-Features which go to 0% life (or stay at 0% from not being assigned a builder) are destroyed, and essentially removed from the tile and the city.

This needs to be further refined and cleaned up, and will happen in #49 .

A new removal type has been added in the city screen for harvest features.

Todo: write up a small default harvest value for buildings which depends on their life and cost.

**Comment by JayToDaBee** [comment]
A default harvest YieldEffect will now be constructed for player improvements if: no explicit HarvestYieldEffect is given, and DefaultHarvestYieldMultiplier, FeatureLife, and MaterialsCost are all specified. A value of 1 for DefaultHarvestYieldMultiplier will allow the player to recuperate the full cost of the building over the course of its harvesting (gonna test 0.4 as a first approximation).

The documentation about harvest yield effects has also been updated. This rounds up what needed to be done for the harvest. This also covers completely what needed to be done by this issue, as we could in principle just define a specialist that would remove 7000 life per turn, and would effectively 'clear' features. Will open another issue if we need a more detailed solution in the future.

Commit: e52c169
