### ISSUE TITLE
Add one spot oriented feature shape

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#43]
See fishing dock feature for use case

**Comment by JayToDaBee** [comment]
Added OneSpotOriented1 and OneSpotOriented2 feature shapes

These shapes are similar to OneSpot but are oriented according to a specific rotation (1 wrt to a single neighbor, and 2 wrt to 2 adjacent neighbors).

This notably modifies the behavior and signature of checkFeaturePlacement to reflect this addition and deal with the rotation cases; this function now returns a rotation or 0 when valid, and -1 when invalid (this lead to some issues also in blueprint) 

getSpotShapeIndices was also modified to always give all spots in the shape, and not skip any invalid ones, which also had some repercussions on blueprints.

The debugging ended up being significantly longer than expected, but I think everything should work. @scaryrabbit try it out with the fishing dock to see if it seems to behave in the expected way and close the issue (or not if it doesnt)

Commit: 4e27f25

**Comment by scaryrabbit** [comment]
Tested the OneSpotOriented2 and it works. The orientation I had to give to my mesh in 3ds max seemed somewhat random, but it is consistent and works in all orientations in game.

**Comment by JayToDaBee** [comment]
Is it off by 120 degrees?

**Comment by scaryrabbit** [comment]
Not sure, but it is possible.

**Comment by JayToDaBee** [comment]
I had to include a 120 degree offset in my tests; but I was using the quarry mesh, so maybe they don't have the same symmetries...? Let me know how much the offset is.

**Comment by JayToDaBee** [comment]
That would be the granite mesh actually*

**Comment by scaryrabbit** [comment]
Yeah, appears to be 120 degrees off from what I would normally expect. Here's a thought I just had : does a one spot oriented feature count as also occupying the orienting spots? 

The granite one is weird because I wanted to use not use the land spot as the pivot. If it counts as part of the feature (and thus prevents other stuff from spawning there, I wont go through the trouble and it'll make things easier on my end. If it isn't part of the feature, then I'll figure it out here :p 

Either way, I would rather you remove that 120 degrees rotation and I make things fit on my end.

**Comment by JayToDaBee** [comment]
> Yeah, appears to be 120 degrees off from what I would normally expect. Here's a thought I just had : does a one spot oriented feature count as also occupying the orienting spots?

No. The only spot which has the feature is the anchor spot (you can btw see this in game by looking at the feature content of spots in the city view).
 
> The granite one is weird because I wanted to use not use the land spot as the pivot. If it counts as part of the feature (and thus prevents other stuff from spawning there, I wont go through the trouble and it'll make things easier on my end. If it isn't part of the feature, then I'll figure it out here :p

Tough luck ;P

> Either way, I would rather you remove that 120 degrees rotation and I make things fit on my end.

Done on master (aafa10d). Was ugly on my side too, that's why I was asking about it. If everything seems in order close the issue!

**Comment by scaryrabbit** [comment]
Apparently, I had exported my granite mesh before properly setting its rotation and never updated it afterwards. If you remove the 120 degrees rotation, everything should work fine on my end.

Made myself a reference sheet to help me figure everything out : 
![feature shapes](https://user-images.githubusercontent.com/6887591/110694404-888e7300-81b6-11eb-97e2-073b905f5331.jpg)

**Comment by scaryrabbit** [comment]
Nope, not sure, so if your code says otherwise, I'll fix it. I thought we always wanted the anchor to be connected to all other spots though.

**Comment by JayToDaBee** [comment]
Yeah, it is... I meant that the anchor spot (which is connected to all others) would be at the bottom, and there would thus be a flat diamond:
       o
o            o
       x
Where x is the anchor

**Comment by JayToDaBee** [comment]
Grrrrr stupid thing just collapsed all my nice spacing


_______o
o____________o
_______x
Ignore the underlines till I figure how to make it keep formatting with spaces

**Comment by scaryrabbit** [comment]
I was going to comment your shape doesn't help at all :p 

I drew it up by the time you posted again. Added spot numbers too. Could you check if everything is right?
![feature shapes](https://user-images.githubusercontent.com/6887591/110695533-056e1c80-81b8-11eb-8a75-7d36d115245d.jpg)

**Comment by JayToDaBee** [comment]
<pre>
             o
o                       o
             x
</pre>

**Comment by JayToDaBee** [comment]
Found it. One should use <_pre_> and <_/pre_> (without underlines)

**Comment by JayToDaBee** [comment]
Yes, this second one is exactly what I would expect from my code, also with the spot numbering.

**Comment by JayToDaBee** [comment]
Although internally the spot numbering starts at 0; don't think you need to think about this I suppose, but you might as well use the same conventions just in case.

**Comment by scaryrabbit** [comment]
If the json numbers spots from 1 to 4, I won't put zeroes in my reference :p

**Comment by JayToDaBee** [comment]
Fair enough.
