### ISSUE TITLE
Resources.json entry that crashes whole feature generation

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#45]
Tried adding a json entry for the fishing dock. While it is in the json, no feature is placed anywhere on the map, but no error message is returned anywhere. Removing this entry makes everything work again.

![Bug](https://user-images.githubusercontent.com/6887591/110529248-04b98580-80e7-11eb-8d7b-716c1ff63033.PNG)

It was copied from the granary feature which works. Tried making BaseReqs identical to the urban district to no avail, tried removing specialists which didn't work either. I'm completely stumped, as far as I can tell similar entries work flawlessly.

Commit : d669cb7 on my NewFeatures branch

**Comment by JayToDaBee** [comment]
There's a missing } ] in the BaseReqs ;)

**Comment by JayToDaBee** [comment]
Let me know if this works. As a general rule, if you see a massive change in all or many features after changing the json, 98% it will be wrong syntax.

**Comment by scaryrabbit** [comment]
Yeah, it works now. Let's not mention the hour I spent looking for that syntax error, shall we? :p
