### ISSUE TITLE
Disentangle SpawnMethod concepts

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#52]
Currently this is used both for spawning instructions AND as a gameplay 'category'. This should be differentiated in the code, using 2 different variables.

**Comment by JayToDaBee** [comment]
SpawnMethod is now a separate field from Category in the feature definition.

SpawnMethod is the way the feature enters play; can be 'Automated' for features which are added by the game, 'Player' for those added by the player, 'Both' if both can happen.

Category is a general container for features which have a similar niche; can be 'Vegetation', 'Deposits', 'PrimaryImprovement', 'SecondaryImprovement', 'Harvest'. Only one feature of each category can be present on any given spot.

Both of these NEED to be defined to a valid option for any instance of the feature to be placeable on the map.

Commit: 910048c
